services:
  web-site:
    image: cryptocurrency-alerting.web-site
    hostname: web-site
    container_name: web-site
    ports:
      - 8000:80
    depends_on:
      - sqlserverdb

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserverdb
    container_name: sql-server
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - 1450:1433
    environment:
      SA_PASSWORD: "SQLServer19"
      ACCEPT_EULA: "Y"

  zookeeper:
    image: bitnami/zookeeper:3.4.12
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:2.1.0
    hostname: kafka
    container_name: kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - kafka_data:/bitnami/kafka
      - $PWD/lipsum.txt:/data/lipsum.txt:ro
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper

  data-collector:
    image: cryptocurrency-alerting.data-collector
    hostname: data-collector
    container_name: data-collector
    depends_on:
      - kafka

  rules-evaluator:
    image: cryptocurrency-alerting.rules-evaluator
    hostname: rules-evaluator
    container_name: rules-evaluator
    depends_on:
      - kafka
      - web-site

volumes:
  sqlvolume:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
